name: pytest_on_python3
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  pytest_on_python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v1.2.0
      # -run: pushd vendor/infogami && git remote -v
      # origin	git://github.com/internetarchive/infogami.git (fetch)
      # origin	git://github.com/internetarchive/infogami.git (push)
      - run: pushd vendor/infogami && git fetch && git pull && git pull --force origin master && popd
      # - run: pushd vendor/infogami && git pull --force origin master && git pull upstream master && popd
      - run: pip install -r requirements_test.txt
      - run: source scripts/test-py3.sh
