name: test_on_docker
on: [pull_request, push]
jobs:
  test_on_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker-compose exec home make test-py || true
      - run: docker-compose exec home npm run test || true
      #  - run: docker-compose exec home make test || true
